language: node_js
node_js:
- '11'
env:
  global:
    secure: IK0Xocjg3gvF7VTrClREwzChKcVHceFFA/vGD8Al9R1B/Xpb35yrVmMq54N33R9s2JtiGHV1oFtgEPC24DF6wdiM7V4EGjDPAg6uw8dUrKkfhQ7/HeX5fd6Xa/nBc6Aej9JdU+1oELMzVp82/ev50qJz84aRmvW0ab+7qKRcW1wZBJDcGSQJR6XjqsmaEAOQnQorxzGANtWLoZYFgAnHkGzLuVKYarz5H3F+lwOvYVC69LH49Y7w4B8y/XrPrgMhVaOGObsLgJaYnbQkMq7EeIYY5ypd07Q/2SnomsLL9TS2HRjZD4zJAoTB/urdR3vhgDST4dhrP4Er5KrtBQRJFbXbdjycnJi/au0GieKytchHnaHEM+PSkiDNWFypoHdSQ16ThrPbN2dSIE8UBKN9742ajIqYyiTpRGJCybK2WzNd2WJQTOEyqUrc057dAOexpqTxXrlFC3MJIxp8RBIfaZTs4ILmQADyTS9MLVX8AUlxeHHimMiCuZl1pg+j/Yz/5nsfC0cfAy/M62186zjLCkoeIfLJStxaCy+m8p4k27rK2mu409d/fXjn66oyzgO9hmh4tMZ7SsLtIYz+ZcVXYtnxvAUu/h4VPsQ/o/1/R/z62S+Uy4FFM61fSUPZp2fA3w8CEhI95cpEMcIDf0EGq1PbrY0FbO/sF989yAopsos=
stages:
#- test
- name: create-tag
  if: branch = master
#- name: init-deploy
#- deploy
jobs:
  include:
  - stage: test
    script: yarn test
  - stage: create-tag
    script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
    - export PATH=$HOME/.yarn/bin:$PATH
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"
    - git remote set-url origin https://herman-rogers:$GITHUB_TOKEN@github.com/herman-rogers/stream-components.git
    - git remote -v # remove
    - git checkout master
    - yarn version --patch
    - export GIT_TAG=`node -p "require('./package.json').version"`
    - git push origin master
    - git push origin $GIT_TAG
  - stage: init-deploy
    script:
    - yarn build
    on:
      tags: true
  - stage: deploy
    provider: npm
    email: herman.rogers@pm.me
    api_key:
      secure: Gtjrs49LWGv+X4c+GDFxX10NNb6JZgblWEW53coiJVLsECJYHRb1LCuyLrne9oT2uMF4OhVgcWwz0Kh1Oj6DMsmMldAMw2ll1B7RR3TNYc0jnR/qHq7fV80EOl0oTM4/vsm+L8HGMskt07MYcAP+sF96As8TM3SUbkeN+0JpnCC5mx9xn6u9eQvapKqvVa9j6yUYa1ZnJ3TdlsNAKEcoUcfzNc4oG8V+CxRB6q2RX+mqLCpOlVW7/asa171A1YTASJlWlNiwtFs41R6SMk9XNtwHHxCZoKWqiu8pyhLOztcaoJc2gJ2HvXz3zBWFgjR2QFvAlavzDrUdLCzr4/xXuM5I5V+N+L78SkO7un3QfvMOTNqLCHWKrPwWkJIMC/XTJWcbBEVUop6JtEU3RlAiQZ7wETxEIGCX209YVJAmX4htdVym6jKJVmdwhMs+iastNR2OEjutyG1h8vb4UU43dGeKhYnBsVAqD//XxCuw90cPQeiIigK3WRQVDPZ9V6UXQ53KpOFqH/oMYZOHbRT0IO4odCYTog6tFhZg1qJWgqwRrnyqgpEZ6mZco6KCz2Keeli/vmzKaa2SWe8sZy/f40iLE/y8+HOtCOBJ+MbDYzHynq2Cs56EebbjzOQ8T6W9fnLfhoFaq7me7/42NsYUp+GPgl9glCFoCqMoCYMtFJs=
    on:
      tags: true
