version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.14.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      - run: yarn test
      - run: yarn build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  release:
    docker:
      - image: circleci/node:11.14.0

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "01:8e:46:bd:cd:ca:90:17:38:42:2d:f6:50:0b:12:82"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Update package.json version
      - run: yarn version --new-version $CIRCLE_TAG && git push origin HEAD:master
      # Builds package.
      - run: npm run build
#      - run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/repo/.npmrc
#      - run: npm publish --access public

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
